### ISSUE TITLE
Object.{entries|values}的支持

### ISSUE THREAD

**Issue by yozosann** [wechat-miniprogram/miniprogram-compat#1]
https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/js-support.html 文档里写了
![image](https://user-images.githubusercontent.com/19776974/115995998-2bd50380-a610-11eb-9a9c-e5559ea002f0.png)
内置了一份corejs，然后这个仓库提供了方法可以查看使用的corejs版本：
![image](https://user-images.githubusercontent.com/19776974/115996044-56bf5780-a610-11eb-9d9f-478be2bc7623.png)
那么按理来说支持基础库2.0.0的机型应该都用的corejs@2.5.1，然后corejs@2.5.1也支持了`Object.{entries|values}`。 那么为什么ios9的机型调用Object.entries()还会报错呢？ 到底哪里能看见一份准确支持的api列表？

**Comment by Tidyzq** [comment]
首先，使用了 corejs@2.5.1 但不代表引入了所有的 corejs 模块（会在 coreJsModules 中列出）。较老的基础库版本只引入了 es6 对应模块，而 Object.entries 是 ES2016 的内容。
另外由于 coreJsModules 仅新版（2.16.1）才能自动生成，旧版需要进行人工追溯，很难考证。因此较老的基础库版本仅能认为只包含 es6 接口。

结论：对于 coreJsModules 为空的情况下，只能认为 browserslist 给出的版本 + es6 接口能够兼容
